name: "build-test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

jobs:
  # make sure build/ci work properly
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v7
    - name: setup node
      uses: actions/setup-node@v6
      with:
        node-version: 24
    - name: build and test
      run: |
        npm install
        npm run all